
import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { BriefcaseIcon, FileTextIcon, MapPinIcon, DownloadIcon, SparklesIcon } from "lucide-react";

const Index = () => {
  const [jobDetails, setJobDetails] = useState("");
  const [generatedResume, setGeneratedResume] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  // Load data from localStorage on component mount
  useEffect(() => {
    const savedJobDetails = localStorage.getItem("jobDetails");
    const savedResume = localStorage.getItem("generatedResume");
    
    if (savedJobDetails) {
      setJobDetails(savedJobDetails);
    }
    if (savedResume) {
      setGeneratedResume(savedResume);
    }
  }, []);

  // Save job details to localStorage whenever it changes
  useEffect(() => {
    if (jobDetails) {
      localStorage.setItem("jobDetails", jobDetails);
    }
  }, [jobDetails]);

  const handleGenerateResume = async () => {
    if (!jobDetails.trim()) return;
    
    setIsGenerating(true);
    console.log("Generating resume with Gemini AI for:", jobDetails);
    
    try {
      // TODO: This will be connected to Google Gemini API
      // For now, we'll simulate the API call
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const mockResume = `
# Resume Generated by AI

## Personal Information
- Based on the job details you provided
- Customized for the specific role and company requirements

## Professional Summary
An experienced professional with skills aligned to the requirements mentioned in your job description. This resume has been tailored to highlight relevant experience and qualifications.

## Key Skills
- Skills extracted and emphasized based on job requirements
- Technical competencies matching the role
- Soft skills relevant to the position

## Work Experience
- Previous roles highlighted to match job requirements
- Achievements quantified and relevant to the target position
- Responsibilities aligned with job description keywords

## Education & Certifications
- Educational background relevant to the role
- Certifications that add value to the application

---
*This resume was generated using AI to match your specific job requirements.*
      `;
      
      setGeneratedResume(mockResume);
      localStorage.setItem("generatedResume", mockResume);
      
    } catch (error) {
      console.error("Error generating resume:", error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleExportPDF = () => {
    if (!generatedResume) {
      alert("Please generate a resume first before exporting.");
      return;
    }
    
    // Create a simple text file download for now
    // In a real implementation, this would generate a proper PDF
    const element = document.createElement("a");
    const file = new Blob([generatedResume], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = "ai-generated-resume.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    
    console.log("Exporting resume as PDF");
  };

  const handleClearData = () => {
    setJobDetails("");
    setGeneratedResume("");
    localStorage.removeItem("jobDetails");
    localStorage.removeItem("generatedResume");
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold text-foreground">Career Jumpstart Hub</h1>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={handleExportPDF}>
                <DownloadIcon className="w-4 h-4 mr-2" />
                Export Resume
              </Button>
              <Button variant="outline" size="sm">
                View Applications
              </Button>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-8">
        <Tabs defaultValue="generate" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="generate" className="flex items-center gap-2">
              <FileTextIcon className="w-4 h-4" />
              Generate Resume
            </TabsTrigger>
            <TabsTrigger value="applications" className="flex items-center gap-2">
              <BriefcaseIcon className="w-4 h-4" />
              Applications
            </TabsTrigger>
            <TabsTrigger value="locations" className="flex items-center gap-2">
              <MapPinIcon className="w-4 h-4" />
              Locations
            </TabsTrigger>
          </TabsList>

          {/* Generate Resume Tab */}
          <TabsContent value="generate" className="mt-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Job Input Form */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <SparklesIcon className="w-5 h-5" />
                    AI Resume Generator
                  </CardTitle>
                  <CardDescription>
                    Paste the complete job details below. Our AI will analyze everything and create a tailored resume for you.
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="jobDetails">Complete Job Details</Label>
                    <Textarea
                      id="jobDetails"
                      placeholder="Paste everything here - job title, company name, location, job description, requirements, etc. The more details you provide, the better your AI-generated resume will be!"
                      className="min-h-[300px]"
                      value={jobDetails}
                      onChange={(e) => setJobDetails(e.target.value)}
                    />
                  </div>
                  
                  <div className="flex gap-2">
                    <Button 
                      onClick={handleGenerateResume} 
                      className="flex-1"
                      disabled={!jobDetails.trim() || isGenerating}
                    >
                      <SparklesIcon className="w-4 h-4 mr-2" />
                      {isGenerating ? "Generating..." : "Generate AI Resume"}
                    </Button>
                    <Button 
                      variant="outline" 
                      onClick={handleClearData}
                      disabled={isGenerating}
                    >
                      Clear
                    </Button>
                  </div>
                </CardContent>
              </Card>

              {/* Resume Preview */}
              <Card>
                <CardHeader>
                  <CardTitle>Generated Resume</CardTitle>
                  <CardDescription>
                    Your AI-customized resume will appear here
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  {generatedResume ? (
                    <div className="space-y-4">
                      <div className="h-[400px] border rounded-lg p-4 overflow-y-auto bg-background">
                        <pre className="whitespace-pre-wrap text-sm">{generatedResume}</pre>
                      </div>
                      <Button onClick={handleExportPDF} className="w-full">
                        <DownloadIcon className="w-4 h-4 mr-2" />
                        Export as PDF
                      </Button>
                    </div>
                  ) : (
                    <div className="h-[400px] border-2 border-dashed border-border rounded-lg flex items-center justify-center text-muted-foreground">
                      {jobDetails.trim() ? (
                        <div className="text-center">
                          <SparklesIcon className="w-12 h-12 mx-auto mb-4 opacity-50" />
                          <p>Click "Generate AI Resume" to create your customized resume</p>
                        </div>
                      ) : (
                        <div className="text-center">
                          <FileTextIcon className="w-12 h-12 mx-auto mb-4 opacity-50" />
                          <p>Enter complete job details to generate your resume</p>
                        </div>
                      )}
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          </TabsContent>

          {/* Applications Tab */}
          <TabsContent value="applications" className="mt-6">
            <Card>
              <CardHeader>
                <CardTitle>Job Applications</CardTitle>
                <CardDescription>
                  Track all your job applications and resume versions
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="text-center py-8 text-muted-foreground">
                  <BriefcaseIcon className="w-12 h-12 mx-auto mb-4 opacity-50" />
                  <p>No applications yet. Generate your first resume to get started!</p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Locations Tab */}
          <TabsContent value="locations" className="mt-6">
            <Card>
              <CardHeader>
                <CardTitle>Job Locations</CardTitle>
                <CardDescription>
                  Filter and view applications by location
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="text-center py-8 text-muted-foreground">
                  <MapPinIcon className="w-12 h-12 mx-auto mb-4 opacity-50" />
                  <p>No locations tracked yet. Start applying to jobs to see location data!</p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </main>
    </div>
  );
};

export default Index;
